
<template>
  <div id="home">
    <ul class="tree">
      <li v-for="item in folders" :key="item.id">
        {{item.name}}
        <ul>
          <li v-for="e in item.children" :key="e.id">
            {{e.name}}
            <ul>
              <li v-for="f in e.children" :key="f.id">{{f.name}}</li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
    <button>add node</button>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
export default {
  name: "Home",
  data() {
    return {
      data: [
        {
          id: 5208259329,
          name: "Online Storage",
          owner_id: 536572161,
          owner_uid: "u536572161u",
          owner: "paulxiaooo@gmail.com",
          user_uid: "u536572161u",
          storagedns: "8534460157540856430",
          storagetype: "SYSTEM",
          physicalstoragetype: "SYSTEM",
          storageservicetype: "AMAZON",
          status: "online",
          remarks: null,
          rootfolder_id: 5208259585,
          rootfolder_name: "Online Storage",
          rootfolder_haschild: "Y",
          rootfolder_twofactored: "N",
          rootfolder_parent_twofactored_ids: [],
          rootbackupfolder_id: 5208260097,
          permissionbitmask: 255,
          twofactored_ids: [],
          assigneduserpoints: [],
          subscribeduser_id: 536572161,
          assigningtype: null,
          mirrorassigning_activated: "N",
          total_quota: 2147483648,
          used_quota_files: 139680103,
          used_quota_backups: 0,
          used_quota_mirrors: 0,
          used_ratio: 7,
          anymodified: 1576726272620923,
          created: 1554804133,
          modified: 1554804133,
          storage_id: 5208259329,
          children: [
            {
              id: 5409084417,
              name: "122",
              owner_id: 536572161,
              owner_uid: "u536572161u",
              owner: "paulxiaooo@gmail.com",
              storage_id: 5208259329,
              storagetype: "SYSTEM",
              storageservicetype: "AMAZON",
              size: 0,
              sizelimit: -1,
              parent_id: 5208259585,
              type: "folder",
              created: 1577427933,
              modified: 1577427933,
              trashed: "N",
              moved_to_trash: "N",
              permissionbitmask: 255,
              usershare_id: null,
              publicshare_id: null,
              shareuser_ids: [],
              users: [],
              contact_ids: [],
              contacts: [],
              permissionbitmasks: [],
              isprivates: [],
              messages: [],
              twofactoreds: [],
              end_dates: [],
              list_ids: [],
              dogtag_ids: [],
              haschild: "N",
              anymodified: 1577427933804268,
              twofactored: "N",
              secured: "N",
              parent_twofactored_ids: [],
              parent_twofactored_shareuser_ids: [],
              cnt_picture: 0,
              cnt_spreadsheet: 0,
              cnt_video: 0,
              cnt_text: 0,
              cnt_pdf: 0,
              cnt_presentation: 0,
              cnt_audio: 0,
              cnt_other: 0,
              netsuiteid: null,
              assigned: "N",
              children: null,
              level: 2,
              icon: " icon-folder icon-folder",
              active: true
            },
            {
              id: 5409084673,
              name: "213",
              owner_id: 536572161,
              owner_uid: "u536572161u",
              owner: "paulxiaooo@gmail.com",
              storage_id: 5208259329,
              storagetype: "SYSTEM",
              storageservicetype: "AMAZON",
              size: 0,
              sizelimit: -1,
              parent_id: 5208259585,
              type: "folder",
              created: 1577428003,
              modified: 1577428003,
              trashed: "N",
              moved_to_trash: "N",
              permissionbitmask: 255,
              usershare_id: null,
              publicshare_id: null,
              shareuser_ids: [],
              users: [],
              contact_ids: [],
              contacts: [],
              permissionbitmasks: [],
              isprivates: [],
              messages: [],
              twofactoreds: [],
              end_dates: [],
              list_ids: [],
              dogtag_ids: [],
              haschild: "N",
              anymodified: 1577428003622380,
              twofactored: "N",
              secured: "N",
              parent_twofactored_ids: [],
              parent_twofactored_shareuser_ids: [],
              cnt_picture: 0,
              cnt_spreadsheet: 0,
              cnt_video: 0,
              cnt_text: 0,
              cnt_pdf: 0,
              cnt_presentation: 0,
              cnt_audio: 0,
              cnt_other: 0,
              netsuiteid: null,
              assigned: "N",
              children: null,
              level: 2,
              icon: " icon-folder icon-folder",
              active: true
            },
            {
              id: 5368871425,
              name: "Letmesee11",
              owner_id: 536572161,
              owner_uid: "u536572161u",
              owner: "paulxiaooo@gmail.com",
              storage_id: 5208259329,
              storagetype: "SYSTEM",
              storageservicetype: "AMAZON",
              size: 6054108,
              sizelimit: -1,
              parent_id: 5208259585,
              type: "folder",
              created: 1572509899,
              modified: 1577427908,
              trashed: "N",
              moved_to_trash: "N",
              permissionbitmask: 255,
              usershare_id: null,
              publicshare_id: 235431169,
              shareuser_ids: [],
              users: [],
              contact_ids: [],
              contacts: [],
              permissionbitmasks: [],
              isprivates: [],
              messages: [],
              twofactoreds: [],
              end_dates: [],
              list_ids: [],
              dogtag_ids: [],
              haschild: "Y",
              anymodified: 1577428711399648,
              twofactored: "N",
              secured: "N",
              parent_twofactored_ids: [],
              parent_twofactored_shareuser_ids: [],
              cnt_picture: 1,
              cnt_spreadsheet: 0,
              cnt_video: 0,
              cnt_text: 0,
              cnt_pdf: 0,
              cnt_presentation: 0,
              cnt_audio: 0,
              cnt_other: 0,
              netsuiteid: null,
              assigned: "N",
              children: [
                {
                  id: 5393364481,
                  name: "test1",
                  owner_id: 536572161,
                  owner_uid: "u536572161u",
                  owner: "paulxiaooo@gmail.com",
                  storage_id: 5208259329,
                  storagetype: "SYSTEM",
                  storageservicetype: "AMAZON",
                  size: 0,
                  sizelimit: -1,
                  parent_id: 5368871425,
                  type: "folder",
                  created: 1575268612,
                  modified: 1577242913,
                  trashed: "N",
                  moved_to_trash: "N",
                  permissionbitmask: 255,
                  usershare_id: null,
                  publicshare_id: null,
                  shareuser_ids: [],
                  users: [],
                  contact_ids: [],
                  contacts: [],
                  permissionbitmasks: [],
                  isprivates: [],
                  messages: [],
                  twofactoreds: [],
                  end_dates: [],
                  list_ids: [],
                  dogtag_ids: [],
                  haschild: "N",
                  anymodified: 1577420391952915,
                  twofactored: "N",
                  secured: "N",
                  parent_twofactored_ids: [],
                  parent_twofactored_shareuser_ids: [],
                  cnt_picture: 0,
                  cnt_spreadsheet: 0,
                  cnt_video: 0,
                  cnt_text: 0,
                  cnt_pdf: 0,
                  cnt_presentation: 0,
                  cnt_audio: 0,
                  cnt_other: 0,
                  netsuiteid: null,
                  assigned: "N",
                  children: null,
                  level: 3,
                  icon: " icon-folder",
                  active: true
                },
                {
                  id: 5384265985,
                  name: "test2",
                  owner_id: 536572161,
                  owner_uid: "u536572161u",
                  owner: "paulxiaooo@gmail.com",
                  storage_id: 5208259329,
                  storagetype: "SYSTEM",
                  storageservicetype: "AMAZON",
                  size: 0,
                  sizelimit: -1,
                  parent_id: 5368871425,
                  type: "folder",
                  created: 1574059830,
                  modified: 1577426998,
                  trashed: "N",
                  moved_to_trash: "N",
                  permissionbitmask: 255,
                  usershare_id: null,
                  publicshare_id: null,
                  shareuser_ids: [],
                  users: [],
                  contact_ids: [],
                  contacts: [],
                  permissionbitmasks: [],
                  isprivates: [],
                  messages: [],
                  twofactoreds: [],
                  end_dates: [],
                  list_ids: [],
                  dogtag_ids: [],
                  haschild: "N",
                  anymodified: 1577426998795881,
                  twofactored: "N",
                  secured: "N",
                  parent_twofactored_ids: [],
                  parent_twofactored_shareuser_ids: [],
                  cnt_picture: 0,
                  cnt_spreadsheet: 0,
                  cnt_video: 0,
                  cnt_text: 0,
                  cnt_pdf: 0,
                  cnt_presentation: 0,
                  cnt_audio: 0,
                  cnt_other: 0,
                  netsuiteid: null,
                  assigned: "N",
                  children: null,
                  level: 3,
                  icon: " icon-folder",
                  active: true
                },
                {
                  id: 5368871681,
                  name: "谢谢23",
                  owner_id: 536572161,
                  owner_uid: "u536572161u",
                  owner: "paulxiaooo@gmail.com",
                  storage_id: 5208259329,
                  storagetype: "SYSTEM",
                  storageservicetype: "AMAZON",
                  size: 6054108,
                  sizelimit: -1,
                  parent_id: 5368871425,
                  type: "folder",
                  created: 1572509903,
                  modified: 1577325234,
                  trashed: "N",
                  moved_to_trash: "N",
                  permissionbitmask: 255,
                  usershare_id: null,
                  publicshare_id: null,
                  shareuser_ids: [],
                  users: [],
                  contact_ids: [],
                  contacts: [],
                  permissionbitmasks: [],
                  isprivates: [],
                  messages: [],
                  twofactoreds: [],
                  end_dates: [],
                  list_ids: [],
                  dogtag_ids: [],
                  haschild: "N",
                  anymodified: 1577325234183802,
                  twofactored: "N",
                  secured: "N",
                  parent_twofactored_ids: [],
                  parent_twofactored_shareuser_ids: [],
                  cnt_picture: 1,
                  cnt_spreadsheet: 0,
                  cnt_video: 0,
                  cnt_text: 0,
                  cnt_pdf: 0,
                  cnt_presentation: 0,
                  cnt_audio: 0,
                  cnt_other: 0,
                  netsuiteid: null,
                  assigned: "N",
                  children: null,
                  level: 3,
                  icon: " icon-folder",
                  active: true
                }
              ],
              level: 2,
              icon: " icon-folder icon-folder",
              expanded: false,
              active: true
            },
            {
              id: 5409084161,
              name: "TT",
              owner_id: 536572161,
              owner_uid: "u536572161u",
              owner: "paulxiaooo@gmail.com",
              storage_id: 5208259329,
              storagetype: "SYSTEM",
              storageservicetype: "AMAZON",
              size: 0,
              sizelimit: -1,
              parent_id: 5208259585,
              type: "folder",
              created: 1577427923,
              modified: 1577427923,
              trashed: "N",
              moved_to_trash: "N",
              permissionbitmask: 255,
              usershare_id: null,
              publicshare_id: null,
              shareuser_ids: [],
              users: [],
              contact_ids: [],
              contacts: [],
              permissionbitmasks: [],
              isprivates: [],
              messages: [],
              twofactoreds: [],
              end_dates: [],
              list_ids: [],
              dogtag_ids: [],
              haschild: "N",
              anymodified: 1577427923530237,
              twofactored: "N",
              secured: "N",
              parent_twofactored_ids: [],
              parent_twofactored_shareuser_ids: [],
              cnt_picture: 0,
              cnt_spreadsheet: 0,
              cnt_video: 0,
              cnt_text: 0,
              cnt_pdf: 0,
              cnt_presentation: 0,
              cnt_audio: 0,
              cnt_other: 0,
              netsuiteid: null,
              assigned: "N",
              children: null,
              level: 2,
              icon: " icon-folder icon-folder",
              active: true
            }
          ],
          type: "storage",
          level: 1,
          icon:
            " icon-storage icon-storage icon-storage icon-storage icon-storage",
          expanded: false,
          active: true
        }
      ]
    };
  },
  computed: {
    ...mapGetters(["folders"])
  },
  created() {
    this.init();
  },
  methods: {
    init() {
      this.$store.commit("INIT_FOLDER");
      this.add(this.data[0]);
    },
    add(node) {
      this.$store.commit("ADD_FOLDER", node);
    }
  }
};
</script>

<style>
.tree {
  text-align: left;
}
</style>
